"""Razorpay: raise a GST invoice for a credit pack, credit the workspace when it is paid.

Prepaid and sales-led. You raise an invoice from the admin page, Razorpay emails it with
a UPI link, the customer pays, and a signed webhook adds the credits. Nobody types a
balance into a spreadsheet, and the tax document is generated by Razorpay so it carries
the GSTIN, HSN/SAC and place-of-supply that Indian law requires.

Four traps are handled deliberately, because each one is a way to give away money:

  one event type   A single payment emits invoice.paid, payment.captured and order.paid,
                   each with its own event id. Subscribe to two and you credit twice
                   while a dedupe on event id sits there looking correct.
  payment id       So the ledger keys on the payment id — the identity of the money —
                   not the event id.
  raw body HMAC    Verified over the exact bytes received, before parsing. Re-serialising
                   parsed JSON passes in dev and fails in prod on key ordering.
  captured only    An authorised payment can still be voided. Credits are issued when
                   the money is actually captured.

    .venv/bin/python billing.py       # self-check: signature and idempotency, no network
"""

import hashlib
import hmac
import json
import os

import credits
import db

# Rupees per credit. One credit is one generated image. Set here rather than per-invoice
# so a price is never accidentally taken from the browser.
RUPEES_PER_CREDIT = 40

# The only event that may add credits. See the module docstring.
CREDITING_EVENT = 'invoice.paid'


def configured() -> bool:
    return bool(os.environ.get('RAZORPAY_KEY_ID')
                and os.environ.get('RAZORPAY_KEY_SECRET'))


def _client():
    import razorpay

    if not configured():
        raise RuntimeError('RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET not set')
    return razorpay.Client(auth=(os.environ['RAZORPAY_KEY_ID'],
                                 os.environ['RAZORPAY_KEY_SECRET']))


def price_paise(credits_count: int) -> int:
    """Integers only. Money in floats is how a rounding error becomes a rounding bug."""
    return credits_count * RUPEES_PER_CREDIT * 100


def raise_invoice(workspace_id: str, credits_count: int) -> dict:
    """Create a GST invoice in Razorpay and email it to the workspace's billing address."""
    if credits_count <= 0:
        raise ValueError('an invoice needs at least one credit')

    workspace = db.query(
        'SELECT name, gstin, billing_email FROM workspaces WHERE id = %s',
        (workspace_id,), one=True)
    if workspace is None:
        raise ValueError('no such workspace')
    if not workspace['billing_email']:
        raise ValueError('this workspace has no billing email — add one first')

    amount = price_paise(credits_count)
    invoice = _client().invoice.create({
        'type': 'invoice',
        'description': f'{credits_count} image credits — Donna Photoshoot',
        'customer': {
            'name': workspace['name'],
            'email': workspace['billing_email'],
            **({'gstin': workspace['gstin']} if workspace['gstin'] else {}),
        },
        'line_items': [{
            'name': 'Donna Photoshoot image credits',
            'description': f'{credits_count} credits, one credit is one generated image',
            'amount': price_paise(1),
            'currency': 'INR',
            'quantity': credits_count,
        }],
        # Carried back on the webhook, so the credits land in the right workspace
        # without trusting anything the payer could influence.
        'notes': {'workspace_id': str(workspace_id), 'credits': str(credits_count)},
        'sms_notify': 1,
        'email_notify': 1,
    })

    db.query(
        """INSERT INTO invoices (workspace_id, razorpay_invoice_id, credits,
                                 amount_paise, status, short_url)
           VALUES (%s, %s, %s, %s, 'issued', %s)""",
        (workspace_id, invoice['id'], credits_count, amount, invoice.get('short_url')))
    return {'invoice_id': invoice['id'], 'short_url': invoice.get('short_url'),
            'credits': credits_count, 'amount_paise': amount}


def verify(raw_body: bytes, signature: str) -> bool:
    """HMAC over the exact bytes received, compared in constant time."""
    secret = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
    if not secret or not signature:
        return False
    expected = hmac.new(secret.encode(), raw_body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def handle(raw_body: bytes, signature: str) -> dict:
    """Process one webhook delivery. Returns what happened, for the log.

    Always succeeds for the caller once the signature checks out — a non-200 makes
    Razorpay retry forever, and a duplicate delivery is normal rather than an error.
    """
    if not verify(raw_body, signature):
        raise PermissionError('bad signature')

    event = json.loads(raw_body)
    kind = event.get('event')
    if kind == 'refund.processed':
        return _refund(event)
    if kind != CREDITING_EVENT:
        return {'ignored': kind}

    payload = event.get('payload', {})
    invoice = payload.get('invoice', {}).get('entity', {})
    payment = payload.get('payment', {}).get('entity', {})

    # Captured, never merely authorised: an authorised payment can still be voided, and
    # credits issued against money that never arrived are not recoverable.
    if payment.get('status') not in ('captured', None):
        return {'ignored': f"payment status {payment.get('status')}"}

    payment_id = payment.get('id') or invoice.get('id')
    notes = invoice.get('notes') or {}
    workspace_id = notes.get('workspace_id')
    count = int(notes.get('credits') or 0)
    if not workspace_id or count <= 0:
        return {'ignored': 'invoice carried no workspace or credit count'}

    # Keyed on the payment id inside credits.purchase, so repeated deliveries of this
    # same payment — or a different event type for it — cannot credit twice.
    balance = credits.purchase(workspace_id, count, payment_id,
                               note=f'invoice {invoice.get("id", "")}')
    db.query(
        """UPDATE invoices SET status = 'paid', paid_at = now(),
                               razorpay_payment_id = %s
            WHERE razorpay_invoice_id = %s AND status <> 'paid'""",
        (payment_id, invoice.get('id')))
    return {'credited': count, 'workspace_id': workspace_id, 'balance': balance}


def _refund(event: dict) -> dict:
    """Money went back, so the credits do too — even into a negative balance.

    This is exactly why the ledger has no non-negative constraint: a ledger that cannot
    record "you owe me four credits" forces somebody to falsify it.
    """
    refund = event.get('payload', {}).get('refund', {}).get('entity', {})
    payment_id = refund.get('payment_id')
    if not payment_id:
        return {'ignored': 'refund carried no payment id'}

    row = db.query(
        'SELECT workspace_id, credits FROM invoices WHERE razorpay_payment_id = %s',
        (payment_id,), one=True)
    if row is None:
        return {'ignored': f'no invoice for payment {payment_id}'}

    with db.tx() as conn:
        credits._append(conn, str(row['workspace_id']), -int(row['credits']),
                        'chargeback', f'refund:{payment_id}',
                        note=f'refund of payment {payment_id}')
    db.query("UPDATE invoices SET status = 'refunded' WHERE razorpay_payment_id = %s",
             (payment_id,))
    return {'reversed': int(row['credits']), 'workspace_id': str(row['workspace_id'])}


def invoices_for(workspace_id: str, limit: int = 50) -> list[dict]:
    return db.query(
        """SELECT razorpay_invoice_id, credits, amount_paise, status, short_url,
                  issued_at, paid_at
             FROM invoices WHERE workspace_id = %s
         ORDER BY issued_at DESC LIMIT %s""", (workspace_id, limit))


def demo() -> None:
    """Self-check: signature handling and idempotency. No network, no Razorpay account."""
    os.environ['RAZORPAY_WEBHOOK_SECRET'] = 'test-secret'
    body = b'{"event":"invoice.paid"}'
    good = hmac.new(b'test-secret', body, hashlib.sha256).hexdigest()

    assert verify(body, good)
    assert not verify(body, 'deadbeef'), 'a wrong signature was accepted'
    assert not verify(body + b' ', good), 'signature must cover the exact bytes'
    assert not verify(body, ''), 'a missing signature was accepted'

    # Re-serialising parsed JSON is the classic way this breaks: it passes in dev and
    # fails in prod on key ordering, so the check must be over the raw bytes.
    reserialised = json.dumps(json.loads(body), separators=(', ', ': ')).encode()
    assert reserialised != body and not verify(reserialised, good)

    try:
        handle(body, 'wrong')
    except PermissionError:
        pass
    else:
        raise AssertionError('an unsigned webhook was processed')

    # Only one event type may credit. Anything else is acknowledged and ignored.
    for other in ('payment.captured', 'order.paid', 'payment.authorized'):
        payload = json.dumps({'event': other}).encode()
        signature = hmac.new(b'test-secret', payload, hashlib.sha256).hexdigest()
        assert handle(payload, signature) == {'ignored': other}, other

    assert price_paise(10) == 10 * RUPEES_PER_CREDIT * 100
    assert isinstance(price_paise(3), int)

    if os.environ.get('DATABASE_URL'):
        import uuid

        db.migrate()
        ws = str(db.query("INSERT INTO workspaces (name, billing_email) "
                          "VALUES ('billing-check','b@test') RETURNING id",
                          one=True)['id'])
        credits.grant(ws, 0 + 5, 'seed')

        paid = json.dumps({
            'event': 'invoice.paid',
            'payload': {
                'invoice': {'entity': {'id': 'inv_1',
                                       'notes': {'workspace_id': ws, 'credits': '100'}}},
                'payment': {'entity': {'id': 'pay_1', 'status': 'captured'}},
            }}).encode()
        signature = hmac.new(b'test-secret', paid, hashlib.sha256).hexdigest()

        first = handle(paid, signature)
        assert first['credited'] == 100, first
        # Razorpay retries. The same payment must not credit twice.
        second = handle(paid, signature)
        assert second['balance'] == first['balance'], 'a retried webhook double-credited'

        total, tail = credits.reconcile(ws)
        assert total == tail, (total, tail)

        db.query('DELETE FROM credit_ledger WHERE workspace_id = %s', (ws,))
        db.query('DELETE FROM invoices WHERE workspace_id = %s', (ws,))
        db.query('DELETE FROM workspaces WHERE id = %s', (ws,))
        db.close()

    print('billing ok')


if __name__ == '__main__':
    demo()
