"""Razorpay: raise a GST invoice for a credit pack, credit the workspace when it is paid.

Prepaid and sales-led. You raise an invoice from the admin page, Razorpay emails it with
a UPI link, the customer pays, and a signed webhook adds the credits. Nobody types a
balance into a spreadsheet, and the tax document is generated by Razorpay so it carries
the GSTIN, HSN/SAC and place-of-supply that Indian law requires.

Four traps are handled deliberately, because each one is a way to give away money:

  one event type   A single payment emits invoice.paid, payment.captured and order.paid,
                   each with its own event id. Subscribe to two and you credit twice
                   while a dedupe on event id sits there looking correct.
  payment id       So the ledger keys on the payment id — the identity of the money —
                   not the event id.
  raw body HMAC    Verified over the exact bytes received, before parsing. Re-serialising
                   parsed JSON passes in dev and fails in prod on key ordering.
  captured only    An authorised payment can still be voided. Credits are issued when
                   the money is actually captured.

    .venv/bin/python billing.py       # self-check: signature and idempotency, no network
"""

import hashlib
import hmac
import json
import os
import time

import credits
import db

# --- what a credit costs, and what it sells for -----------------------------------
#
# One credit is one generated image. Set here rather than per-invoice so a price can
# never be taken from the browser.
#
# Derived rather than guessed, from measured numbers (2026-08-20, USD/INR 95.75):
#
#   fal nano-banana-pro/edit @2K          $0.150000   published rate
#   Anthropic detection, 1/3 of a shoot   $0.000821   measured 2299 in + 33 out, haiku
#   S3 storage 30 days + PUT              $0.000127   ~5MB PNG
#   App Runner active CPU                 $0.000567   ~1 min at 0.5 vCPU
#   forex markup on USD billing 3%        $0.004545
#                                         ---------
#   marginal                              $0.156061 = Rs 14.94
#
# Plus Rs 2,283/month of fixed cost (App Runner memory, RDS, Secrets Manager) which is
# pure volume arithmetic. At the planning figure of 100 shoots a month — 300 credits —
# that is Rs 7.84 a credit, so all-in cost is Rs 22.78. Priced at cost + 50%, grossed up
# for the Razorpay fee, that is Rs 35.
#
# NOTE: AWS is currently billing $0 because account credits absorb it. The Rs 2,283
# appears when those run out, so it is costed in deliberately rather than ignored.
MARGINAL_COST_RUPEES = 14.94        # per credit, excludes fixed monthly costs
RUPEES_PER_CREDIT = 35              # ex-GST. 18% GST is added on the invoice.

# GST. Razorpay computes the tax itself and prints it as its own line, which is what
# makes the document a tax invoice a B2B customer can claim input credit against — the
# entire reason for using Razorpay Invoices rather than a payment link.
#
# Sending these is necessary but NOT sufficient: Razorpay only computes tax once GST is
# configured on the account (Dashboard > Settings > Tax/GST, GSTIN-gated). Until then it
# accepts and stores both fields and returns tax_amount = 0, i.e. it silently issues an
# invoice with no tax line. price_paise() is therefore the ex-GST figure in both cases,
# and the customer's total is that plus whatever Razorpay adds.
GST_BASIS_POINTS = 1800             # 18%, as Razorpay wants it: hundredths of a percent

# SAC 998386 is "photographic and videographic processing services". An AI image
# generation service is arguably 998434 (on-line software) instead, and the answer
# changes the rate a customer can reclaim. Confirm with the CA before the first live
# invoice; it is one constant.
SAC_CODE = '998386'

# What a customer can buy without talking to anyone. Keyed by name, never by amount:
# /api/checkout takes a pack key and resolves the size here, so a client that posts
# credits=99999 gets a KeyError rather than a discount.
PACKS = {
    'starter': 30,      # 10 shoots
    'studio': 100,      # 33 shoots
    'house': 300,       # 100 shoots — the volume the price was derived at
}

# How long a self-serve invoice stays payable. Short on purpose: an invoice-first
# checkout is what buys the GST document, and the cost of that shape is an abandoned
# cart leaving an issued invoice open. Expiry closes them without anyone doing it by
# hand. Long enough that someone can go and find their UPI PIN.
INVOICE_TTL_MINUTES = 30

# The only event that may add credits. See the module docstring.
CREDITING_EVENT = 'invoice.paid'


def configured() -> bool:
    return bool(os.environ.get('RAZORPAY_KEY_ID')
                and os.environ.get('RAZORPAY_KEY_SECRET'))


def _client():
    import razorpay

    if not configured():
        raise RuntimeError('RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET not set')
    return razorpay.Client(auth=(os.environ['RAZORPAY_KEY_ID'],
                                 os.environ['RAZORPAY_KEY_SECRET']))


def price_paise(credits_count: int) -> int:
    """Integers only. Money in floats is how a rounding error becomes a rounding bug."""
    return credits_count * RUPEES_PER_CREDIT * 100


def raise_invoice(workspace_id: str, credits_count: int,
                  expire_by: int | None = None) -> dict:
    """Create a GST invoice in Razorpay and email it to the workspace's billing address.

    An ISSUED invoice carries an order_id, which is what Checkout opens against — that
    is what lets self-serve have both a modal and a tax invoice without hand-rolling
    the document. Drafts have order_id NULL, so this must never create one.
    """
    if credits_count <= 0:
        raise ValueError('an invoice needs at least one credit')

    workspace = db.query(
        'SELECT name, gstin, billing_email FROM workspaces WHERE id = %s',
        (workspace_id,), one=True)
    if workspace is None:
        raise ValueError('no such workspace')
    if not workspace['billing_email']:
        raise ValueError('this workspace has no billing email — add one first')

    amount = price_paise(credits_count)
    invoice = _client().invoice.create({
        'type': 'invoice',
        'description': f'{credits_count} image credits — Donna Photoshoot',
        'customer': {
            'name': workspace['name'],
            'email': workspace['billing_email'],
            **({'gstin': workspace['gstin']} if workspace['gstin'] else {}),
        },
        'line_items': [{
            'name': 'Donna Photoshoot image credits',
            'description': f'{credits_count} credits, one credit is one generated image',
            'amount': price_paise(1),
            'currency': 'INR',
            'quantity': credits_count,
            # The amount above is ex-GST, so the tax is added on top rather than
            # carved out of it. Getting this backwards silently cuts the margin by 18%.
            'tax_inclusive': False,
            'tax_rate': GST_BASIS_POINTS,
            'sac_code': SAC_CODE,
        }],
        # Carried back on the webhook, so the credits land in the right workspace
        # without trusting anything the payer could influence.
        'notes': {'workspace_id': str(workspace_id), 'credits': str(credits_count)},
        'sms_notify': 1,
        'email_notify': 1,
        # Unix seconds. Passed in rather than computed from a clock inside the payload
        # so the caller decides how long the cart lives.
        'expire_by': expire_by or int(time.time() + INVOICE_TTL_MINUTES * 60),
    })

    db.query(
        """INSERT INTO invoices (workspace_id, razorpay_invoice_id, razorpay_order_id,
                                 credits, amount_paise, status, short_url)
           VALUES (%s, %s, %s, %s, %s, 'issued', %s)""",
        (workspace_id, invoice['id'], invoice.get('order_id'), credits_count, amount,
         invoice.get('short_url')))
    # Surfaced rather than assumed. Razorpay returns tax_amount = 0 when GST is not
    # configured on the account, and an invoice with no tax line looks entirely normal
    # until a customer's CA rejects it — so the caller gets told, every time.
    tax_paise = int(invoice.get('tax_amount') or 0)
    return {'invoice_id': invoice['id'], 'short_url': invoice.get('short_url'),
            'order_id': invoice.get('order_id'),
            'credits': credits_count, 'amount_paise': amount,
            'tax_paise': tax_paise,
            'gross_paise': int(invoice.get('gross_amount') or amount),
            'gst_applied': tax_paise > 0}


def verify(raw_body: bytes, signature: str) -> bool:
    """HMAC over the exact bytes received, compared in constant time."""
    secret = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
    if not secret or not signature:
        return False
    expected = hmac.new(secret.encode(), raw_body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def handle(raw_body: bytes, signature: str) -> dict:
    """Process one webhook delivery. Returns what happened, for the log.

    Always succeeds for the caller once the signature checks out — a non-200 makes
    Razorpay retry forever, and a duplicate delivery is normal rather than an error.
    """
    if not verify(raw_body, signature):
        raise PermissionError('bad signature')

    event = json.loads(raw_body)
    kind = event.get('event')
    if kind == 'refund.processed':
        return _refund(event)
    if kind != CREDITING_EVENT:
        return {'ignored': kind}

    payload = event.get('payload', {})
    invoice = payload.get('invoice', {}).get('entity', {})
    payment = payload.get('payment', {}).get('entity', {})

    # Captured, never merely authorised: an authorised payment can still be voided, and
    # credits issued against money that never arrived are not recoverable.
    if payment.get('status') not in ('captured', None):
        return {'ignored': f"payment status {payment.get('status')}"}

    payment_id = payment.get('id') or invoice.get('id')
    notes = invoice.get('notes') or {}
    workspace_id = notes.get('workspace_id')
    count = int(notes.get('credits') or 0)
    if not workspace_id or count <= 0:
        return {'ignored': 'invoice carried no workspace or credit count'}

    # Keyed on the payment id inside credits.purchase, so repeated deliveries of this
    # same payment — or a different event type for it — cannot credit twice.
    balance = credits.purchase(workspace_id, count, payment_id,
                               note=f'invoice {invoice.get("id", "")}')
    db.query(
        """UPDATE invoices SET status = 'paid', paid_at = now(),
                               razorpay_payment_id = %s
            WHERE razorpay_invoice_id = %s AND status <> 'paid'""",
        (payment_id, invoice.get('id')))
    return {'credited': count, 'workspace_id': workspace_id, 'balance': balance}


def _refund(event: dict) -> dict:
    """Money went back, so the credits do too — even into a negative balance.

    This is exactly why the ledger has no non-negative constraint: a ledger that cannot
    record "you owe me four credits" forces somebody to falsify it.
    """
    refund = event.get('payload', {}).get('refund', {}).get('entity', {})
    payment_id = refund.get('payment_id')
    if not payment_id:
        return {'ignored': 'refund carried no payment id'}

    row = db.query(
        'SELECT workspace_id, credits FROM invoices WHERE razorpay_payment_id = %s',
        (payment_id,), one=True)
    if row is None:
        return {'ignored': f'no invoice for payment {payment_id}'}

    with db.tx() as conn:
        credits._append(conn, str(row['workspace_id']), -int(row['credits']),
                        'chargeback', f'refund:{payment_id}',
                        note=f'refund of payment {payment_id}')
    db.query("UPDATE invoices SET status = 'refunded' WHERE razorpay_payment_id = %s",
             (payment_id,))
    return {'reversed': int(row['credits']), 'workspace_id': str(row['workspace_id'])}


def invoices_for(workspace_id: str, limit: int = 50) -> list[dict]:
    return db.query(
        """SELECT razorpay_invoice_id, credits, amount_paise, status, short_url,
                  issued_at, paid_at
             FROM invoices WHERE workspace_id = %s
         ORDER BY issued_at DESC LIMIT %s""", (workspace_id, limit))


def demo() -> None:
    """Self-check: signature handling and idempotency. No network, no Razorpay account."""
    os.environ['RAZORPAY_WEBHOOK_SECRET'] = 'test-secret'
    body = b'{"event":"invoice.paid"}'
    good = hmac.new(b'test-secret', body, hashlib.sha256).hexdigest()

    assert verify(body, good)
    assert not verify(body, 'deadbeef'), 'a wrong signature was accepted'
    assert not verify(body + b' ', good), 'signature must cover the exact bytes'
    assert not verify(body, ''), 'a missing signature was accepted'

    # Re-serialising parsed JSON is the classic way this breaks: it passes in dev and
    # fails in prod on key ordering, so the check must be over the raw bytes.
    reserialised = json.dumps(json.loads(body), separators=(', ', ': ')).encode()
    assert reserialised != body and not verify(reserialised, good)

    try:
        handle(body, 'wrong')
    except PermissionError:
        pass
    else:
        raise AssertionError('an unsigned webhook was processed')

    # Only one event type may credit. Anything else is acknowledged and ignored.
    for other in ('payment.captured', 'order.paid', 'payment.authorized'):
        payload = json.dumps({'event': other}).encode()
        signature = hmac.new(b'test-secret', payload, hashlib.sha256).hexdigest()
        assert handle(payload, signature) == {'ignored': other}, other

    assert price_paise(10) == 10 * RUPEES_PER_CREDIT * 100
    assert isinstance(price_paise(3), int)

    # Packs are what a stranger can buy unattended, so the table gets checked rather
    # than trusted. A pack that is not a whole number of shoots leaves credits stranded
    # that the customer paid for and cannot spend on the thing they came for.
    assert PACKS, 'no packs means no self-serve checkout'
    for name, size in PACKS.items():
        assert isinstance(size, int) and size > 0, name
        # Deliberately NOT a whole number of shoots. Credits are fungible — a reshoot
        # and a retouch cost one each — so the remainder on a 100-credit pack is spendable
        # rather than stranded, and 100 is a better number to put on a card than 99.
        assert size >= credits.COST['shoot'], (
            f'pack {name!r} cannot buy even one shoot')
    # No volume discount is encoded yet; if one is added, this is where it gets checked
    # against MARGINAL_COST_RUPEES rather than discovered in a bank statement.
    assert len(set(PACKS.values())) == len(PACKS), 'two packs are the same size'
    assert 0 < INVOICE_TTL_MINUTES <= 24 * 60, 'a cart that lives a day is not a cart'

    # The price has to clear the marginal cost with room to spare. This is the check
    # that fires if fal raises its rate or the rupee moves and nobody re-does the maths
    # — otherwise the first anyone hears of selling below cost is the bank balance.
    assert RUPEES_PER_CREDIT > MARGINAL_COST_RUPEES * 1.5, (
        f'Rs {RUPEES_PER_CREDIT}/credit does not clear Rs {MARGINAL_COST_RUPEES} '
        f'marginal cost by 50% — re-derive the price')
    # And it must cover the fixed base at the volume it was priced for.
    FIXED_RUPEES_MONTH, PLANNED_CREDITS_MONTH = 2283, 300
    all_in = MARGINAL_COST_RUPEES + FIXED_RUPEES_MONTH / PLANNED_CREDITS_MONTH
    assert RUPEES_PER_CREDIT >= all_in * 1.5 * 0.98, (
        f'Rs {RUPEES_PER_CREDIT} is under cost+50% (Rs {all_in * 1.5:.2f}) at '
        f'{PLANNED_CREDITS_MONTH} credits/month')
    # Break-even volume, for the record: below this the fixed base eats the margin.
    breakeven = FIXED_RUPEES_MONTH / (RUPEES_PER_CREDIT / 1.5 - MARGINAL_COST_RUPEES)
    assert breakeven < PLANNED_CREDITS_MONTH, breakeven

    if os.environ.get('DATABASE_URL'):
        import uuid

        db.migrate()
        ws = str(db.query("INSERT INTO workspaces (name, billing_email) "
                          "VALUES ('billing-check','b@test') RETURNING id",
                          one=True)['id'])
        credits.grant(ws, 0 + 5, 'seed')

        paid = json.dumps({
            'event': 'invoice.paid',
            'payload': {
                'invoice': {'entity': {'id': 'inv_1',
                                       'notes': {'workspace_id': ws, 'credits': '100'}}},
                'payment': {'entity': {'id': 'pay_1', 'status': 'captured'}},
            }}).encode()
        signature = hmac.new(b'test-secret', paid, hashlib.sha256).hexdigest()

        first = handle(paid, signature)
        assert first['credited'] == 100, first
        # Razorpay retries. The same payment must not credit twice.
        second = handle(paid, signature)
        assert second['balance'] == first['balance'], 'a retried webhook double-credited'

        total, tail = credits.reconcile(ws)
        assert total == tail, (total, tail)

        db.query('DELETE FROM credit_ledger WHERE workspace_id = %s', (ws,))
        db.query('DELETE FROM invoices WHERE workspace_id = %s', (ws,))
        db.query('DELETE FROM workspaces WHERE id = %s', (ws,))
        db.close()

    print('billing ok')


if __name__ == '__main__':
    demo()
